### ISSUE TITLE
error by using LongVU_Llama3_2_3B video 

### ISSUE THREAD

**Issue by GrahLnn** [Vision-CAIR/LongVU#3]
I try to use LongVU_Llama3_2_3B video, but I got this

```
Loading Cambrian from ./checkpoints/longvu_llama
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/grahlnn/LongVU/infer.py", line 16, in <module>
    tokenizer, model, image_processor, context_len = load_pretrained_model(
  File "/home/grahlnn/LongVU/longvu/builder.py", line 165, in load_pretrained_model
    model = CambrianLlamaForCausalLM.from_pretrained(
  File "/home/grahlnn/miniconda3/envs/longvu/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3235, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/home/grahlnn/miniconda3/envs/longvu/lib/python3.10/site-packages/transformers/configuration_utils.py", line 610, in from_pretrained
    return cls.from_dict(config_dict, **kwargs)
  File "/home/grahlnn/miniconda3/envs/longvu/lib/python3.10/site-packages/transformers/configuration_utils.py", line 772, in from_dict
    config = cls(**config_dict)
  File "/home/grahlnn/miniconda3/envs/longvu/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
    self._rope_scaling_validation()
  File "/home/grahlnn/miniconda3/envs/longvu/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 182, in _rope_scaling_validation
    raise ValueError(
ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 32.0, 'high_freq_factor': 4.0, 'low_freq_factor': 1.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}
```

How can I use LongVU_Llama3_2_3B video?

**Comment by xiaoqian-shen** [comment]
Can you double check your transformers version? Please also refer to this [post](https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct/discussions/15).

**Comment by GrahLnn** [comment]
Thanks, I update transformers and vllm, now working.
